http:
  port: 5000
  maxHeaderBytes: 1
  readTimeout: 10s
  writeTimeout: 10s

mongo:
  databaseName: sport_kit

auth:
  accessTokenTTL: 2h
  refreshTokenTTL: 720h #30 days
  verificationCodeLength: 8

limiter:
  rps: 10
  burst: 20
  ttl: 10m